version: '3'

services:

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    volumes:
      - ./api-gateway:/www/api-gateway
      - /www/api-gateway/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - ./api-gateway/.env
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}   
    depends_on: 
      - rabbitmq 

  profile_ms:
    container_name: profile_ms
    build:
      context: ./profile/app-microservices
    volumes:
      - ./profile/app-microservices:/www/profile_ms
      - /www/profile_ms/node_modules
    command: npm run start:dev
    env_file:
      - ./profile/app-microservices/.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_PROFILE}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - DATABASE_URL=${DATABASE_URL_PROFILE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER} 
    depends_on:
      - profile_db
      - rabbitmq  

  auth_ms:
    container_name: auth_ms
    build:
      context: ./auth/app-microservices
    volumes:
      - ./auth/app-microservices:/www/auth_ms
      - /www/auth_ms/node_modules
    command: npm run start:dev
    env_file:
      - ./auth/app-microservices/.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST_AUTH}
      - DATABASE_URL=${DATABASE_URL_AUTH}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}  
    depends_on:
      - auth_db  
      - rabbitmq   

  profile_db:
    container_name: profile_db
    image: postgres:12-alpine
    hostname: profile_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB_PROFILE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5431:5432
    volumes:
      - ./pg_data_profile:/var/lib/postgresql/data 

  auth_db:
    container_name: auth_db
    image: postgres:12-alpine
    hostname: auth_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB_AUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - ./pg_data_auth:/var/lib/postgresql/data      

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    volumes:
      - ./rabbit_data:/var/lib/rabbitmq 
    ports:
      - 5672:5672
      - 15671:15672

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    hostname: pgadmin 
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL} 
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin_d–∞ta:/var/lib/pgadmin  
    ports:
      - 5050:80

volumes:
  pg_data_auth:
  pg_data_profile:
  rabbit_data:

  